---

- name: "[setting branch]"
  set_fact:
    freckle_branch: "{{ freckle_item_metadata['remote_branch'] }}"
  when: freckle_item_metadata.get('remote_branch', False)

- name: "[pretty print branch]"
  set_fact:
    branch_string: ", '{{ freckle_branch }}' branch"
  when: freckle_branch is defined

- name: "[pretty print branch]"
  set_fact:
    branch_string: ""
  when: freckle_branch is not defined

- name: "checking out '{{ freckle_item_metadata.remote_url }}' {{ branch_string }}"
  git:
    repo: "{{ freckle_item_metadata.remote_url }}"
    dest: "{{ freckle_local_parent_path }}/{{ freckle_item_metadata.local_name }}"
    version: "{{ freckle_branch | default(omit) }}"
  become: "{{ freckle_item_metadata.checkout_become }}"
