- name: '[calculating packages to install]'
  set_fact:
    freckelize_install_packages: "{{ freckelize_profiles_metadata | create_package_list_from_profiles_metadata(pkg_mgr) }}"

- name: "[calculating extra package managers]"
  set_fact:
    freckelize_extra_package_managers: "{{ freckelize_profiles_metadata | create_extra_pkg_mgrs_list }}"

- name: "[preapring base packages]"
  include_role:
    name: freckles-io.install-packages
  vars:
    profile_name: "all folder"
    package_install_list: "{{ freckelize_install_packages }}"
    extra_pkg_mgrs: "{{ freckelize_extra_package_managers }}"
  when: "not dotfiles_no_package_install"
