---
- name: "[processing folder permissions]"
  include_tasks: folder_permissions.yml
  vars:
    freckle_folder_path: "{{ freckelize_folder_metadata['folder_metadata']['full_path'] }}"
    freckle_folder_metadata: "{{ freckelize_folder_metadata['folder_vars'] }}"
  when: "freckelize_folder_metadata['folder_vars'].get('change_owner', False)"
  with_items:
      - "{{ freckelize_freckle_metadata.values() }}"
  loop_control:
    loop_var: freckelize_folder_metadata

- name: "[putting folders in place]"
  include_tasks: "stage_folder_{{ freckelize_folder_metadata['folder_vars']['staging_method'] }}.yml"
  vars:
    freckle_folder_path: "{{ freckelize_folder_metadata['folder_metadata']['full_path'] }}"
    freckle_folder_metadata: "{{ freckelize_folder_metadata['folder_vars'] }}"
  when: "freckelize_folder_metadata['folder_vars'].get('staging_method', False)"
  with_items:
      - "{{ freckelize_freckle_metadata.values() }}"
  loop_control:
    loop_var: freckelize_folder_metadata

# - name: "executing generic freckle tasks"
  # include_tasks: "freckle-generic.yml"

- name: "[including profile specific tasks]"
  include_tasks: "profile.yml"
  vars:
    freckles_profile_folders: "{{ freckelize_profiles_metadata[freckelize_profile_name] }}"
  with_items:
      - "{{ profile_order }}"
  loop_control:
    loop_var: freckelize_profile_name
