---
# tasks per profiles
- name: "starting adapter '{{ freckles_profile_name }}'"
  debug: msg="Starting adapter '{{ freckles_profile_name }}'"

- name: "[starting adater init: {{ freckles_profile_name }}]"
  include_tasks: "{{ playbook_dir }}/../task_lists/{{ freckle_init_item['target'] }}"
  vars:
      global_profile_vars: "{{ freckles_profile_folders | flatten_vars_filter }}"
  with_items:
    - "{{ adapters_files_map.get(freckles_profile_name, {}).get('init', []) }}"
  loop_control:
    loop_var: freckle_init_item

- name: "[starting adapter tasks: {{ freckles_profile_name }}]"
  # include_tasks: "items-{{ freckles_profile_name }}.yml"
  include_tasks: "tasks_freckle_profiles.yml"
  vars:
    freckle_path: "{{ freckle_loop_item.key }}"
    freckle_folder_name: "{{ freckle_loop_item.key | basename }}"
    freckle_owner: "{{ freckle_global_folder_vars[freckle_loop_item.key]['owner'] }}"
    freckle_vars: "{{ freckle_loop_item.value.vars | flatten_vars_filter }}"
    freckle_vars_raw: "{{ freckle_loop_item.value }}"
    freckle_folder_vars: "{{ freckle_global_folder_vars[freckle_loop_item.key] }}"
  with_dict: "{{ freckles_profile_folders }}"
  loop_control:
    loop_var: freckle_loop_item
