---
# tasks per profiles
- name: "starting adapter '{{ freckelize_profile_name }}'"
  debug: msg="Starting adapter '{{ freckelize_profile_name }}'"

- debug: var=freckles_profile_folders
- debug: var=adapters_files_map

- name: "[starting adater init: {{ freckelize_profile_name }}]"
  include_tasks: "{{ playbook_dir }}/../task_lists/{{ freckle_init_item['target'] }}"
  vars:
      profile_vars: "{{ freckles_profile_folders | flatten_profile_vars }}"
      profile_vars_folders: "{{ freckles_profile_folders }}"
  with_items:
    - "{{ adapters_files_map.get(freckelize_profile_name, {}).get('init', []) }}"
  loop_control:
    loop_var: freckle_init_item

- name: "[starting adapter tasks: {{ freckelize_profile_name }}]"
  include_tasks: "tasks_freckle_profiles.yml"
  vars:
    freckle_path: "{{ profile_folder_metadata['folder_metadata']['full_path'] }}"
    freckle_vars: "{{ profile_folder_metadata['vars'] }}"
    freckle_folder_metadata: "{{ profile_folder_metadata['folder_metadata'] }}"
    freckle_extra_vars: "{{ profile_folder_metadata['extra_vars'] }}"
    freckle_base_vars: "{{ freckelize_freckle_metadata[profile_folder['folder_metadata']['full_path']] }}"
  with_items:
    - "{{ freckles_profile_folders }}"
  loop_control:
    loop_var: profile_folder_metadata
