---
# tasks per profiles
- name: "starting adapter '{{ freckelize_profile_name }}'"
  debug: msg="Starting adapter '{{ freckelize_profile_name }}'"

- name: "[starting adapter tasks: {{ freckelize_profile_name }}]"
  include_tasks: "tasks_freckle_profiles.yml"
  vars:
    freckle_path: "{{ profile_folder_metadata['folder_metadata']['full_path'] }}"
    freckle_vars: "{{ profile_folder_metadata['vars'] }}"
    freckle_profile_vars: "{{ profile_folder_metadata['folder_vars'] }}"
    freckle_folder_metadata: "{{ profile_folder_metadata['folder_metadata'] }}"
    freckle_extra_vars: "{{ profile_folder_metadata['extra_vars'] }}"
    freckle_base_vars: "{{ freckelize_freckle_metadata[profile_folder_metadata['folder_metadata']['full_path']]['vars'] }}"
  with_items:
    - "{{ freckles_profile_folders }}"
  loop_control:
    loop_var: profile_folder_metadata
