- name: "[setting project name]"
  set_fact:
    python_dev_project_name: "{{ python_dev_project_path | project_name_filter }}"
  when: python_dev_project_name is not defined

# TODO: check whether setup type is valid
- name: "[setting setuptools command]"
  set_fact:
    setup_command: "python setup.py {{ python_dev_setuptools_command }}"
  when: "python_dev_setup_type == 'setuptools'"

- name: "[setting pip install command]"
  set_fact:
    setup_command: "pip install -e ."
  when: "python_dev_setup_type == 'pip'"

- fail: msg="Could not determine setup method. 'python_dev_setup' needs to be either 'pip' or 'setuptools'"
  when: not setup_command

# TODO: check whether env type is valid

- name: "[including conda tasks]"
  include_tasks: python-env-conda.yml
  when: "python_dev_env_type == 'conda'"

- name: "[including virtualenv tasks]"
  include_tasks: python-env-virtualenv.yml
  when: "python_dev_env_type == 'virtualenv'"
